import Constants from 'expo-constants'

const AMPLITUDE_API_KEY_TEST = '2e48b765aa8663f304b9413cf97f4e86'
const AMPLITUDE_API_KEY_PROD = '2e48b765aa8663f304b9413cf97f4e86'

export enum EVENTS {
  FINISHED_COURSE = 'FINISHED_COURSE',
  PLAYED_COURSE = 'PLAYED_COURSE',
  PLAYED_WARMUP = 'PLAYED_WARMUP',
  PRESSED_LEAVE_COURSE_BTN = 'PRESSED_LEAVE_COURSE_BTN',
  SHOWED_COURSE_DESCRIPTION = 'SHOWED_COURSE_DESCRIPTION',
  SHOWED_FORGOT_PASSWORD_PAGE = 'SHOWED_FORGOT_PASSWORD_PAGE',
  SHOWED_FORGOT_PASSWORD_OTP_PAGE = 'SHOWED_FORGOT_PASSWORD_OTP_PAGE',
  SHOWED_HOME_PAGE = 'SHOWED_HOME_PAGE',
  SHOWED_LOGIN_PAGE = 'SHOWED_LOGIN_PAGE',
  SHOWED_ONBOARDING_OBJECTIVES_PAGE = 'SHOWED_ONBOARDING_OBJECTIVES_PAGE',
  SHOWED_ONBOARDING_SEX_PAGE = 'SHOWED_ONBOARDING_SEX_PAGE',
  SHOWED_SIGNUP_PAGE = 'SHOWED_SIGNUP_PAGE',
  SHOWED_SIGNUP_OTP_PAGE = 'SHOWED_SIGNUP_OTP_PAGE',
}

export function getAmplitudeApiKey() {
  const { releaseChannel } = Constants.manifest || {releaseChannel: undefined}

  if (Boolean(releaseChannel) === false) {
    return AMPLITUDE_API_KEY_TEST
  }

  if (releaseChannel.indexOf('prod') !== -1) {
    return AMPLITUDE_API_KEY_PROD
  }

  return AMPLITUDE_API_KEY_TEST
}